version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8.14-management
    hostname: rabbitmq
    volumes:
      # https://www.rabbitmq.com/configure.html
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672
