repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

environments:
  default:
    values:
    - default.yaml

releases:
  # https://bitnami.com/stack/postgresql/helm
  # https://github.com/bitnami/bitnami-docker-postgresql
  - name: postgresql
    namespace: {{ .Values.namespace }}
    chart: bitnami/postgresql
    # https://artifacthub.io/packages/helm/bitnami/postgresql
    version: 11.6.2
    atomic: true
    set:
      - name: image.tag
        value: {{ .Values.image.tag }}
