repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

environments:
  default:
    values:
    - default.yaml

releases:
  # https://bitnami.com/stack/postgresql/helm
  # https://github.com/bitnami/bitnami-docker-postgresql
  - name: postgresql
    chart: bitnami/postgresql
    version: 11.6.2
    # https://artifacthub.io/packages/helm/bitnami/postgresql
    namespace: {{ .Values.namespace }}
    atomic: true
    set:
      - name: image.tag
        value: {{ .Values.image.tag }}
      - name: auth.username
        value: {{ .Values.auth.username }}
      - name: auth.password
        value: {{ .Values.auth.password }}
      - name: auth.database
        value: {{ .Values.auth.database }}
      - name: auth.postgresPassword
        value: {{ .Values.auth.database }}
