Vagrant.configure(2) do |config|
  config.vm.box = "vagrant-docker-centos7-dck-km-hm"
  config.vm.hostname = "vag-centos7-dck-km-hm-v1-15"

  config.vm.provider "virtualbox" do |v|
    v.name = "vag-centos7-dck-km-hm-v1-15"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  config.vm.synced_folder ".", "/vagrant"

  config.vm.synced_folder "./.minikube/", "/root/.minikube/"
  config.vm.synced_folder "./.kube/", "/root/.kube/"
  config.vm.synced_folder "./.helm/", "/root/.helm/"
  config.vm.synced_folder "./conf/docker/", "/etc/docker/"

  config.vm.synced_folder "~/.minikube/cache", "/root/.minikube/cache"
  config.vm.synced_folder "~/VMs/_archives_", "/home/vagrant/VMs/_archives_"
  config.vm.synced_folder "~/VMs/__docker-registry__", "/var/lib/registry/docker/registry/v2/"

  config.vm.synced_folder "~/git/bash-fwk", "/home/vagrant/git/bash-fwk"

  config.vm.provision "shell", inline: <<-SHELL
    if [[ -f "/home/vagrant/git/bash-fwk/setup.bash" ]]; then
      (cd /home/vagrant/git/bash-fwk && . setup.bash)
      . /home/vagrant/.bash_profile

      dckimportfolder k8s
      kmstartversion v1.15.5

      # https://computingforgeeks.com/install-and-configure-docker-registry-on-centos-7/
      # inst_docker_registry
      # dckregstart
      # dckregstatus

      # https://www.cyberciti.biz/faq/sudo-append-data-text-to-file-on-linux-unix-macos/
      # echo '127.0.0.1   local_domain' | sudo tee -a /etc/hosts
    fi
  SHELL

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
