version: '3'

services:
  redis:
    image: redis:alpine
    hostname: cache
    restart: always
    ports:
      - ${CACHE_PORT:-6379}:6379
    volumes:
      - $PWD/db/data:/var/lib/redis
      - $PWD/db/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server # --requirepass pass
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 30s
      interval: 3s
      retries: 5
    networks:
      - cache-network

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - ${CACHE_UI_PORT:-8001}:8001
    volumes:
      - ./db/redisinsight:/db
    depends_on:
      - redis
    networks:
      - cache-network

networks:
  cache-network: