version: "3.9"
services:
  redis:
    image: "redis:alpine"
    hostname: "cache"
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server # --requirepass pass
    environment:
      - REDIS_REPLICATION_MODE=master
