spring:
  main:
    allow-bean-definition-overriding: true

flink:
  job-name: "FlinkStreamingSpringBoot"
  job-manager-url: "localhost"
  job-manager-port: 28081
  remote-env-jar-files:
    - "build/libs/flink-pipeline-0.1.0-SNAPSHOT.jar"
  max-client-rest-request-size-bytes: 2000000000
  terminate: true
  termination-grace-period-ms: 30000
