# https://hub.docker.com/_/alpine
FROM alpine:3.11.3

ARG SIMPLE_ARG='args'

ARG DEFAULT_TEXT='default text'
ENV DEFAULT_TEXT=$DEFAULT_TEXT

RUN echo "RUN echo: ${DEFAULT_TEXT} ${SIMPLE_ARG}"

ENTRYPOINT echo "ENTRYPOINT echo > env: $DEFAULT_TEXT arg: $SIMPLE_ARG \n"
