apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-bridge.fullname" . }}
  labels:
    {{- include "nginx-bridge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.service.httpPort }}
    - name: https
      protocol: TCP
      port: 443
      targetPort: {{ .Values.service.httpsPort }}
  selector:
    {{- include "nginx-bridge.selectorLabels" . | nindent 4 }}
