version: '3'

services:
  # https://github.com/docker-library/docs/tree/master/mysql
  mysql:
    image: mysql:8.0.22
    platform: linux/x86_64
    # image: mariadb:10.5.8

    # container_name: mysql
    hostname: database
    restart: always
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      # MAKE SURE YOU RUN mysqlstart FROM run_scripts.bash TO INIT DATA FOLDER
      # Use this option to persist the MySQL DBs in a shared volume.
      - $PWD/db/data:/var/lib/mysql
      - $PWD/db/init_sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD:-admin}
      MYSQL_DATABASE: ${DB_NAME:-db}
      MYSQL_USER: ${APP_USER:-username}
      MYSQL_PASSWORD: ${APP_PASSWORD:-pass}

      ## Use % to allow remote access to all addresses. 
      ## Generally not recommended by some people to allow for root.
      MYSQL_ROOT_HOST: "%"

      # This allows ip ranges from 192.168.0.49 to 192.168.0.54 to connect to root
      #MYSQL_ROOT_HOST: "192.168.0.49/255.255.255.248"
    command:
      - "--log-error-verbosity"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--skip-character-set-client-handshake"
      # https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_secure_file_priv
      # Check with : SELECT @@GLOBAL.secure_file_priv; || SHOW VARIABLES LIKE "secure_file_priv";
      - "--secure-file-priv="
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 1s
      timeout: 1s
      retries: 60
    networks:
      - db-network

  phpmyadmin:
    # container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.9
    restart: always
    ports:
      - ${DB_UI_PORT:-8008}:80
    environment:
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD:-admin}
      MYSQL_USER: ${APP_USER:-username}
      MYSQL_PASSWORD: ${APP_PASSWORD:-pass}
      PMA_HOST: database
    depends_on:
      - mysql
    networks:
      - db-network

networks:
  db-network:
