VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(2) do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  #config.vm.box = "williamyeh/ubuntu-trusty64-docker"

  config.vm.box = "williamyeh/centos7-docker"
  config.vm.hostname = "vagrant-docker-centos7"

  #config.ssh.username = 'root'
  #config.ssh.password = 'vagrant'
  #config.ssh.insert_key = 'true'

  config.vm.synced_folder "~/git/bash-fwk", "/home/vagrant/git/bash-fwk"
  config.vm.provision "shell", inline: <<-SHELL
    if [[ -f "/home/vagrant/git/bash-fwk/setup.bash" ]]; then
      (cd /home/vagrant/git/bash-fwk && . setup.bash)
    fi
  SHELL

  config.vm.synced_folder ".", "/vagrant"

  config.vm.synced_folder "~/VMs/_archives_", "/home/vagrant/VMs/_archives_"

  #config.vm.provision "shell", inline:"sudo apt-get update"
  #config.vm.provision :docker
  #config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yaml", compose_version: "1.22.0", rebuild: true, run: "always"

  config.vm.provision "shell", inline: <<-SHELL
    # Install tools and register docker repo, based on https://docs.docker.com/install/linux/docker-ce/centos/
    sudo yum install -y yum-utils device-mapper-persistent-data lvm2
    sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    # Install local files
    inst docker-ce-cli-19.03.5-3.el7.x86_64.rpm docker-ce-19.03.5-3.el7.x86_64.rpm containerd.io-1.2.10-3.2.el7.x86_64.rpm
  SHELL

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: "192.168.50.100"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
end
