---
version: '2'
services:
  registry:
    image: ${REGISTRY_IMAGE}
    restart: always
    container_name: docker-registry
#    labels:
#      - "PROJECT=registry"
    ports:
      - 443:5000
    networks:
      - docker-registry-network
    environment:
      # https://docs.docker.com/registry/configuration/
      # ONLY FOR RECEIVING IMAGES
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_HTTP_SECRET=COMMON_SECRET
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/server.key
    volumes:
      # https://kubernetes.io/docs/concepts/containers/images/
      - ./conf/docker:/etc/docker/
      - ./conf/registry/certs/:/certs
      - /var/lib/registry/:/var/lib/registry
  registry-ui:
    image: ${REGISTRY_UI_IMAGE}
    container_name: registry-ui
#    labels:
#      - "PROJECT=registry"
    ports:
      - 3000:3000
    networks:
      - docker-registry-network
    environment:
      - ENV_DOCKER_REGISTRY_PORT=5000
      - ENV_DOCKER_REGISTRY_HOST=docker-registry
    depends_on:
      - registry
networks:
  docker-registry-network:
    driver: bridge
#    labels:
#      - "PROJECT=registry"