---
version: '3'
services:
  registry:
    image: registry:2
    restart: always
    container_name: docker-registry
#    labels:
#      - "PROJECT=registry"
    ports:
      - 443:5000
    networks:
      - docker-registry-network
    environment:
      # https://docs.docker.com/registry/configuration/
      # ONLY FOR RECEIVING IMAGES
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_HTTP_SECRET=COMMON_SECRET
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/server.key
    volumes:
      # https://kubernetes.io/docs/concepts/containers/images/
      - ./conf/docker:/etc/docker/
      - ./conf/registry/certs/:/certs
      - /var/lib/registry/:/var/lib/registry
  registry-ui:
    image: parabuzzle/craneoperator:latest
    restart: always
    container_name: registry-ui
#    labels:
#      - "PROJECT=registry"
    ports:
      - 3000:80
    environment:
      - REGISTRY_HOST=docker-registry
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=http
      - SSL_VERIFY=false
      - USERNAME=admin
      - PASSWORD=mypassword
    depends_on:
      - registry
    networks:
      - docker-registry-network
networks:
  docker-registry-network:
    driver: bridge
#    labels:
#      - "PROJECT=registry"