VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(2) do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  #config.vm.box = "williamyeh/ubuntu-trusty64-docker"

  config.vm.box = "vagrant-docker-centos7"
  config.vm.hostname = "vagrant-docker-registry"

  #config.ssh.username = 'root'
  #config.ssh.password = 'vagrant'
  #config.ssh.insert_key = 'true'

  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "private_network", ip: "192.168.50.100"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.synced_folder "~/git/bash-fwk", "/home/vagrant/git/bash-fwk"
  config.vm.provision "shell", inline: <<-SHELL
    if [[ -f "/home/vagrant/git/bash-fwk/setup.bash" ]]; then
      (cd /home/vagrant/git/bash-fwk && . setup.bash)
    fi
  SHELL

  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", inline:"sudo apt-get update"

  config.vm.synced_folder "~/VMs/_archives_", "/home/vagrant/VMs/_archives_"
  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yaml", compose_version: "1.22.0", rebuild: true, run: "always"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
